spring.application.name=sunuvtc-backend

spring.datasource.url=jdbc:mysql://localhost:3306/db_sunuvtc?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8080

# Augmenter la limite de profondeur de nesting
spring.jackson.stream-write-constraints.max-nesting-depth=2000

# Désactiver la détection des références circulaires
spring.jackson.deserialization.fail-on-ignored-properties=false
spring.jackson.deserialization.fail-on-unknown-properties=false

# Ignorer les propriétés null
spring.jackson.default-property-inclusion=non_null



